# docker-compose.yml
version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: py_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - db_volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    ports:
      - "3306:3306"
    env_file:
      - ./secrets/secrets.env

  web:
    build: .
    container_name: web 
    ports:
      - "5000:5000"
    volumes:
      - web_volume:/app
    networks:
      - frontend 
      - backend
    depends_on:
      - db
    env_file:
      - ./secrets/secrets.env

volumes:
  db_volume:
  web_volume:
networks:
  frontend:
  backend: 
    internal: true  